### ISSUE TITLE
Show better errors when `[data-page]` does not exist

### ISSUE THREAD

**Issue by westoque** [lucasmazza/page.js#11]
In my CI test. It was hard to figure out that one of my layouts' `<body>` tag was missing the `[data-page]` attribute. The error showed something like:

```
Uncaught TypeError: Cannot read property 'split' of null
```

I suggest something like:

```
Uncaught Error: <body> does not have a [data-page] attribute
```

What do you think? I have `page.js` version that uses the one mentioned above. Let me know if you want this and I can submit a PR.

Thanks.

**Comment by lucasmazza** [comment]
@westoque yes - we should fail better. If you want please feel free to send a Pull Request! :)
